config/routes.rb
Rails.application.routes.draw do
  get 'account', to: 'users#show', as: 'account'
  delete 'delete_account', to: 'users#delete', as: 'delete_account'
  get 'edit_username', to: 'users#edit_username', as: 'edit_username'
  patch 'update_username', to: 'users#update_username', as: 'update_username'

  resources :users,
    controller: 'users',
    only: 'create'

  resources :notebooks do
    resources :notes
  end

  root 'welcome#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.persisted?
      can :manage, Notebook, user_id: user.id
      can :manage, User
    end
  end
end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :notebook
end

app/models/notebook.rb
class Notebook < ActiveRecord::Base
  belongs_to :user
  has_many :notes
end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User
  has_many :notebooks

  validates :username, length: { maximum: 40, too_long: "must have at most %{count} characters" }

  def display_name
    username.presence || email
  end

  def get_username
    username.presence || "not defined"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  check_authorization unless: :clearance_controller?

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, :alert => exception.message
  end

  def clearance_controller?
    false
  end
end

app/controllers/notebooks_controller.rb
class NotebooksController < ApplicationController
  authorize_resource

  def index
    @notebooks = current_user.notebooks
  end

  def show
    @notebook = Notebook.find(params[:id])
    authorize! :show, @notebook
  end

  def new
    @notebook = Notebook.new
  end

  def create
    @notebook = Notebook.new notebook_params
    @notebook.user = current_user
    if @notebook.save
      redirect_to notebook_path(@notebook)
    else
      render :new
    end
  end

  def edit
    @notebook = Notebook.find params[:id]
    authorize! :edit, @notebook
  end

  def destroy
    Notebook.find(params[:id]).destroy
    redirect_to root_path
  end

  def update
    @notebook = Notebook.find params[:id]
    if @notebook.update(notebook_params)
      redirect_to(@notebook)
    else
      render "edit"
    end
  end

  private

  def notebook_params
    params.require(:notebook).permit(:description)
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  skip_authorization_check

  def index
    @note = Note.all
  end

  def show
    @note = Note.find(params[:id])
  end

  def new
    @note = Note.new
  end

  def create
    @note = Note.new note_params
    @note.notebook_id = params[:notebook_id]
    if @note.save
      redirect_to notebook_path(@note.notebook)
    else
      render :new
    end
  end

  def edit
    @note = Note.find params[:id]
  end

  def destroy
    @note = Note.find params[:id]
    @note.destroy
    redirect_to notebook_path(@note.notebook)
  end

  def update
    @note = Note.find params[:id]
    if @note.update(note_params)
      redirect_to notebook_path(@note.notebook)
    else
      render "edit"
    end
  end

  private

  def note_params
    params.require(:note).permit(:description,:text)
  end
end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController
  authorize_resource
  skip_authorize_resource :only => :create

  def show
  end

  def create
    @user = user_from_params

    if @user.save
      sign_in @user
      redirect_to '/'
    else
      render template: 'users/new'
    end
  end

  def delete
    User.find(current_user.id).destroy
    flash[:alert] = 'You deleted your account successfuly.'
    redirect_to root_path
  end

  def edit_username
    @user = current_user
  end

  def update_username
    @user = current_user
    if @user.update(username_params)
      flash[:notice] = 'You edited your username successfuly.'
      redirect_to account_path
    else
      flash[:alert] = 'An error ocurred.'
      render 'edit_username'
    end
  end

  private

  def user_from_params
    user_params = params[:user] || Hash.new
    username = user_params.delete(:username)
    email = user_params.delete(:email)
    password = user_params.delete(:password)

    Clearance.configuration.user_model.new(user_params).tap do |user|
      user.username = username
      user.email = email
      user.password = password
    end
  end

  def username_params
    params.require(:user).permit(:username)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_authorization_check
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def form_errors(object)
    render :partial => 'shared/object_errors', :locals => { :object => object }
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Evernote</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">
          <span class="glyphicon glyphicon-pencil"></span>
          <span class="brand-name">Ever(y)note</span>
        </a>
      </div>
      <section id="session-info">
        <% if signed_in? %>
          Welcome, <%= link_to current_user.display_name, account_path %> ·
          <%= link_to 'Sign out', sign_out_path, :method => :delete %>
        <% else %>
          <%= link_to 'Sign in', sign_in_path %> ·
          <%= link_to 'Sign up', sign_up_path %>
        <% end %>
      </section>
    </div>
  </div>
    <main>
        <div class="container">
          <% unless flash.empty? %>
            <div id="flash">
              <% flash.each do |key, value| %>
                <div class="flash <%= key %>"><%= value %></div>
              <% end %>
            </div>
          <% end %>
          <%= yield %>
        </div>
    </main>
</body>
</html>

app/views/notebooks/_form.html.erb
<%= form_for @notebook do |form| %>
  <%= form.label :description %>
  <%= form.text_field :description %>
  <%= form.submit %>
<% end %>

app/views/notebooks/edit.html.erb
<h1>Edit Notebook</h1>

<%= render "form" %>

app/views/notebooks/index.html.erb
<div class="intro">
	<h1>Notebooks</h1>

	<table class="notebook-display">
	  <% @notebooks.each do |notebook|%>
	    <tr>
	      <td class="notebook-description"><h4><%= notebook.description %></h4></td>
	      <td><%= link_to "Show" , notebook %></td>
	      <td><%= link_to "Rename" , edit_notebook_path(notebook) %></td>
	      <td><%= link_to "Delete" , notebook, method: :delete %></td>
	    </tr>
	  <%end%>
	</table>

<%= link_to "New Notebook", new_notebook_path %>
</div>

app/views/notebooks/new.html.erb
<h1>Create Notebook</h1>

<%= render "form" %>

app/views/notebooks/show.html.erb
<div class="intro">

	<table class="notebook-display">

	    <tr>
	      <td class="notebook-description"><h4><%= @notebook.description %></h4></td>
	      <!-- <td><%= link_to "Delete" , @notebook, method: :delete %></td> -->
	    </tr>
	</table>
  <h2>NOTES:</h2>
  <ul>
    <% @notebook.notes.each do |note| %>
      <li>
          <%= note.text %>
          <%= link_to 'Edit note', edit_notebook_note_path(notebook_id:  @notebook.id, id: note.id) %>
          <%= link_to 'Delete note', notebook_note_path(notebook_id:  @notebook.id, id: note.id), method: :delete %>
      </li>
    <% end %>
  </ul>
  <%= link_to "Add note", new_notebook_note_path(notebook_id:  @notebook.id) %>
  <br/>
  <br/>
	<%= link_to "Back", notebooks_path %>
</div>

app/views/notes/_form.html.erb
<%= form.label :text %>
<%= form.text_field :text %>

<%= form.submit %>

app/views/notes/edit.html.erb
<h1>Edit note:</h1>

<%= form_for @note, url: notebook_note_path(params[:notebook_id],params[:id]) do |form| %>
  <%= render 'form', form: form %>
<% end %>

app/views/notes/index.html.erb
index notes

app/views/notes/new.html.erb
<h1>Create Note</h1>

<%= form_for @note, url: notebook_notes_path(params[:notebook_id]) do |form| %>
  <%= render "form", form: form %>
<% end %>

app/views/shared/_object_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(object.errors.count, "error") %> in form</h2>
 
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, :type => 'email' %>
</div>

<div class="text-field">
  <%= form.label :username %>
  <%= form.text_field :username %>
</div>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

app/views/users/edit_username.html.erb
<h2>Edit Your Username</h2>
<%= simple_form_for @user, url: {controller: 'users', action: 'update_username'} do |f| %>
  <%= f.input :username %>

  <%= f.submit 'save' %>
<% end %>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t('.title') %></h2>

  <%= form_for @user do |form| %>
    <%= render :partial => '/users/form', :object => form %>

    <div class="submit-field">
      <%= form.submit %>
    </div>

    <div class="other-links">
      <%= link_to t('.sign_in'), sign_in_path %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="intro">
  <h2>Your Account</h2>
  <table>
    <tr>
      <td class="sign-message">You are signed in via your email (<b><%= current_user.email %></b>)</td>
    </tr>
    <tr>
      <td>Username</td>
      <td>
          <%= current_user.get_username %>
      </td>
      <td>
        <%= link_to 'edit', edit_username_path, id: 'edit_username_link' %>
      </td>
    </tr>
    <tr>
      <td colspan="2">Password</td>
      <td>
        <%= link_to 'edit', edit_user_password_path(current_user.id) %>
      </td>
    </tr>
    <tr>
      <td colspan="2">Account</td>
      <td><%= link_to 'delete', delete_account_path, id: 'delete_account_link', confirm: 'Are you sure?', method: 'delete' %></td>
    </tr>
  </table> 
</div>

app/views/welcome/index.html.erb
<section class="intro">
    <h1>Welcome</h1>
    <hr>
    <div class="row">
        <div class="intro-left col-md-6">
            <h2>Everynote helps you remember everything across all the computers, phones and tablets you use.</h2>
            
            <section id="sign-index" class="sign-form " role="form" id="session-info">
                <% if signed_in? %>
                <h4>Signed in as:</h4><%= current_user.email %><br />
                <%= link_to 'Sign out', sign_out_path, :method => :delete %>
                <%= link_to 'Notebooks', notebooks_path %>
                <% else %>
                <%= link_to 'Sign in', sign_in_path %>
                <% end %>
            </section>

        </div>
        <div class="intro-right col-md-4 col-md-offset-2">
            <span class="glyphicon glyphicon-ok-circle"></span>    
        </div>
    </div>    
</section>